DROP TABLE IF EXISTS `Wines`;
DROP TABLE IF EXISTS `Dishes`;
DROP TABLE IF EXISTS `WinePairings`;

CREATE TABLE `Wines` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `vintage` VARCHAR(255) NOT NULL,
    `image` VARCHAR(255) NOT NULL,
    `type` VARCHAR(255) NOT NULL
);


CREATE TABLE `Dishes` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `type` VARCHAR(255) NOT NULL
);

CREATE TABLE `WinePairings` (
    `WineId` INT NULL,
    `DisheId` INT NULL,
    FOREIGN KEY (WineId) REFERENCES Wines(id) ON DELETE CASCADE,
    FOREIGN KEY (DisheId) REFERENCES Dishes(id) ON DELETE CASCADE
);

